"use client";
import {FormEvent,useEffect,useRef,useState} from "react";import {useParams} from "next/navigation";import Link from "next/link";import {createClient} from "@/lib/supabase/client";import {useAuth} from "../../components/AuthProvider";
type Msg={id:string;conversation_id:string;sender_id:string;body:string;created_at:string;read_at:string|null};
export default function Chat(){const {conversationId}=useParams<{conversationId:string}>();const {user,loading}=useAuth();const [messages,setMessages]=useState<Msg[]>([]),[body,setBody]=useState(""),[error,setError]=useState("");const bottom=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(!user||!conversationId)return;const s=createClient();let active=true;const load=async()=>{const {data,error}=await s.from("messages").select("*").eq("conversation_id",conversationId).order("created_at",{ascending:true}).range(0,199);if(active){if(error)setError(error.message);setMessages((data??[]) as Msg[])}};void load();const ch=s.channel(`chat:${conversationId}`).on("postgres_changes",{event:"INSERT",schema:"public",table:"messages",filter:`conversation_id=eq.${conversationId}`},p=>setMessages(prev=>prev.some(x=>x.id===p.new.id)?prev:[...prev,p.new as Msg])).subscribe(status=>{if(status==="CHANNEL_ERROR")setError("Live chat connection failed. Refresh to retry.")});return()=>{active=false;void s.removeChannel(ch)}},[user,conversationId]);
 useEffect(()=>bottom.current?.scrollIntoView({behavior:"smooth"}),[messages]);
 async function send(e:FormEvent){e.preventDefault();const text=body.trim();if(!text||!user)return;setBody("");const {error}=await createClient().from("messages").insert({conversation_id:conversationId,sender_id:user.id,body:text});if(error){setError(error.message);setBody(text)}}
 async function markRead(){if(!user)return;await createClient().from("messages").update({read_at:new Date().toISOString()}).eq("conversation_id",conversationId).neq("sender_id",user.id).is("read_at",null)}
 useEffect(()=>{if(user&&conversationId)void markRead()},[user,conversationId]);
 if(loading)return <main className="mx-auto max-w-3xl px-5 py-16">Loading…</main>;
 return <main className="mx-auto max-w-3xl px-5 py-8"><Link href="/messages" className="font-bold underline">← All conversations</Link><div className="card mt-5 flex min-h-[65vh] flex-col p-4"><div className="flex-1 space-y-3 overflow-y-auto p-3">{messages.length===0&&<p className="py-16 text-center text-[var(--muted)]">Start the conversation. Keep addresses, passwords and other sensitive information private.</p>}{messages.map(m=><div key={m.id} className={`flex ${m.sender_id===user?.id?"justify-end":"justify-start"}`}><div className={`max-w-[80%] rounded-2xl px-4 py-3 ${m.sender_id===user?.id?"bg-[var(--leaf)] text-white":"border bg-white"}`}><p className="whitespace-pre-wrap break-words">{m.body}</p><small className="mt-1 block opacity-70">{new Date(m.created_at).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</small></div></div>)}<div ref={bottom}/></div>{error&&<p className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<form onSubmit={send} className="mt-3 flex gap-2"><input required maxLength={2000} value={body} onChange={e=>setBody(e.target.value)} placeholder="Write a message…" className="min-w-0 flex-1 rounded-xl border p-3"/><button className="rounded-xl bg-[var(--ink)] px-5 font-black text-white">Send</button></form></div></main>}
