"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient, type Session, type User } from "@supabase/supabase-js";

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL || "https://treqbtzxxzlwzucdoiqo.supabase.co";
const SUPABASE_KEY = process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY || "sb_publishable_yAxVJKn1obRcVFx6eq4fAQ_0Kgn5ZJm";
const supabase = createClient(SUPABASE_URL, SUPABASE_KEY);

type FoodStatus = "available" | "reserved" | "collected" | "expired" | "removed";
type ClaimStatus = "pending" | "accepted" | "declined" | "cancelled" | "completed";
type Food = { id:string; donor_id:string; title:string; description:string; food_type:string; quantity:string; dietary_info:string|null; city:string; region:string|null; country:string; pickup_start:string; pickup_end:string; status:FoodStatus; image_url:string|null; created_at:string; };
type Claim = { id:string; listing_id:string; claimant_id:string; message:string; status:ClaimStatus; created_at:string; food_listings?:{title:string;city:string;country:string;donor_id:string}|null; };

const foodTypes = ["All","Prepared meals","Bakery","Produce","Groceries","Drinks","Other"];
const countries = ["Malaysia","Singapore","India","Indonesia","United Kingdom","United States","Australia","Canada","Other"];
function dateLabel(value:string){return new Intl.DateTimeFormat(undefined,{day:"numeric",month:"short",hour:"numeric",minute:"2-digit"}).format(new Date(value));}
function timeLeft(value:string){const mins=Math.max(0,Math.round((new Date(value).getTime()-Date.now())/60000));if(mins<60)return `${mins}m left`;const hours=Math.floor(mins/60);return `${hours}h ${mins%60}m left`;}
function safeText(value:FormDataEntryValue|null){return String(value||"").trim();}

export default function GiveBack(){
 const [session,setSession]=useState<Session|null>(null); const [user,setUser]=useState<User|null>(null); const [foods,setFoods]=useState<Food[]>([]); const [claims,setClaims]=useState<Claim[]>([]);
 const [tab,setTab]=useState<"discover"|"donate"|"dashboard">("discover"); const [query,setQuery]=useState(""); const [type,setType]=useState("All"); const [country,setCountry]=useState("All countries"); const [selected,setSelected]=useState<Food|null>(null); const [authMode,setAuthMode]=useState<"signin"|"signup">("signin"); const [authOpen,setAuthOpen]=useState(false); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [notice,setNotice]=useState<{kind:"ok"|"error";text:string}|null>(null);
 const refresh=async(currentUser=user)=>{setLoading(true);const {data,error}=await supabase.from("food_listings").select("*").eq("status","available").gt("pickup_end",new Date().toISOString()).order("created_at",{ascending:false});if(error)setNotice({kind:"error",text:error.message});setFoods((data||[]) as Food[]);if(currentUser){const {data:mine}=await supabase.from("food_claims").select("*,food_listings(title,city,country,donor_id)").eq("claimant_id",currentUser.id).order("created_at",{ascending:false});const {data:incoming}=await supabase.from("food_claims").select("*,food_listings!inner(title,city,country,donor_id)").eq("food_listings.donor_id",currentUser.id).order("created_at",{ascending:false});const m=new Map<string,Claim>();[...(mine||[]),...(incoming||[])].forEach(c=>m.set(c.id,c as Claim));setClaims([...m.values()]);}else setClaims([]);setLoading(false);};
 useEffect(()=>{supabase.auth.getSession().then(({data})=>{setSession(data.session);setUser(data.session?.user??null);refresh(data.session?.user??null);});const {data:l}=supabase.auth.onAuthStateChange((_e,next)=>{setSession(next);setUser(next?.user??null);refresh(next?.user??null);});return()=>l.subscription.unsubscribe();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
 const filtered=useMemo(()=>foods.filter(f=>{const h=`${f.title} ${f.description} ${f.food_type} ${f.city} ${f.country} ${f.dietary_info||""}`.toLowerCase();return h.includes(query.toLowerCase().trim())&&(type==="All"||f.food_type===type)&&(country==="All countries"||f.country===country);}),[foods,query,type,country]);
 const owned=useMemo(()=>foods.filter(f=>f.donor_id===user?.id),[foods,user]); const incoming=useMemo(()=>claims.filter(c=>c.food_listings?.donor_id===user?.id),[claims,user]); const outgoing=useMemo(()=>claims.filter(c=>c.claimant_id===user?.id),[claims,user]);
 const requireAuth=()=>{if(user)return true;setAuthMode("signin");setAuthOpen(true);return false;};
 async function submitAuth(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setNotice(null);const fd=new FormData(e.currentTarget);const email=safeText(fd.get("email"));const password=safeText(fd.get("password"));const name=safeText(fd.get("name"));try{if(authMode==="signup"){const {data,error}=await supabase.auth.signUp({email,password,options:{data:{display_name:name||"Community member"}}});if(error)throw error;if(!data.session){setAuthOpen(false);setNotice({kind:"ok",text:"Account created. Check your email to verify it, then sign in."});}else{setAuthOpen(false);setNotice({kind:"ok",text:"Welcome to GiveBack Food Rescue."});}}else{const {error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;setAuthOpen(false);setNotice({kind:"ok",text:"Welcome back."});}}catch(error:unknown){setNotice({kind:"error",text:error instanceof Error?error.message:"Authentication failed."});}finally{setBusy(false);}}
 async function signOut(){await supabase.auth.signOut();setTab("discover");setNotice({kind:"ok",text:"Signed out safely."});}
 async function donate(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!requireAuth()||!user)return;setBusy(true);setNotice(null);const fd=new FormData(e.currentTarget);const date=safeText(fd.get("pickup_date"));const start=new Date(`${date}T${safeText(fd.get("pickup_start"))}`);const end=new Date(`${date}T${safeText(fd.get("pickup_end"))}`);if(end<=start){setNotice({kind:"error",text:"Pickup end time must be after the start time."});setBusy(false);return;}try{const {error}=await supabase.from("food_listings").insert({donor_id:user.id,title:safeText(fd.get("title")),description:safeText(fd.get("description")),food_type:safeText(fd.get("food_type")),quantity:safeText(fd.get("quantity")),dietary_info:safeText(fd.get("dietary_info"))||null,city:safeText(fd.get("city")),region:safeText(fd.get("region"))||null,country:safeText(fd.get("country")),pickup_start:start.toISOString(),pickup_end:end.toISOString(),image_url:safeText(fd.get("image_url"))||null});if(error)throw error;e.currentTarget.reset();setTab("discover");await refresh(user);setNotice({kind:"ok",text:"Your surplus food is now visible to people who can use it."});}catch(error:unknown){setNotice({kind:"error",text:error instanceof Error?error.message:"Could not publish the food listing."});}finally{setBusy(false);}}
 async function claimFood(e:FormEvent<HTMLFormElement>,food:Food){e.preventDefault();if(!requireAuth()||!user)return;if(food.donor_id===user.id){setNotice({kind:"error",text:"You cannot claim your own listing."});return;}setBusy(true);try{const {error}=await supabase.from("food_claims").insert({listing_id:food.id,claimant_id:user.id,message:safeText(new FormData(e.currentTarget).get("message"))});if(error)throw error;setSelected(null);await refresh(user);setNotice({kind:"ok",text:"Request sent. The donor can review it from My GiveBack."});}catch(error:unknown){setNotice({kind:"error",text:error instanceof Error?error.message:"Could not send your request."});}finally{setBusy(false);}}
 async function acceptClaim(c:Claim){if(!user||c.food_listings?.donor_id!==user.id)return;setBusy(true);try{const {data:reserved,error:re}=await supabase.from("food_listings").update({status:"reserved"}).eq("id",c.listing_id).eq("donor_id",user.id).eq("status","available").select("id").maybeSingle();if(re)throw re;if(!reserved)throw new Error("This food has already been reserved by someone else.");const {error}=await supabase.from("food_claims").update({status:"accepted"}).eq("id",c.id);if(error)throw error;await supabase.from("food_claims").update({status:"declined"}).eq("listing_id",c.listing_id).eq("status","pending").neq("id",c.id);await refresh(user);setNotice({kind:"ok",text:"Claim accepted. Coordinate pickup safely and mark it collected after handover."});}catch(error:unknown){setNotice({kind:"error",text:error instanceof Error?error.message:"Could not accept the request."});}finally{setBusy(false);}}
 async function updateClaim(c:Claim,status:ClaimStatus){if(!user)return;setBusy(true);try{const {error}=await supabase.from("food_claims").update({status}).eq("id",c.id);if(error)throw error;if(status==="cancelled")await supabase.from("food_listings").update({status:"available"}).eq("id",c.listing_id).eq("status","reserved");if(status==="completed")await supabase.from("food_listings").update({status:"collected"}).eq("id",c.listing_id).eq("status","reserved");await refresh(user);setNotice({kind:"ok",text:status==="completed"?"Handover marked complete. Food rescued.":`Request ${status}.`});}catch(error:unknown){setNotice({kind:"error",text:error instanceof Error?error.message:"Could not update the request."});}finally{setBusy(false);}}

 return <main className="min-h-screen bg-[var(--paper)]">
 <header className="sticky top-0 z-40 border-b border-[var(--line)] bg-[rgba(248,247,241,.92)] backdrop-blur-xl"><div className="mx-auto flex max-w-7xl items-center justify-between gap-4 px-5 py-4 lg:px-8"><button onClick={()=>setTab("discover")} className="flex items-center gap-3 text-left"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-[var(--leaf)] text-xl font-black text-white">↗</span><span><span className="block text-lg font-black">GiveBack</span><span className="block text-[11px] font-bold uppercase tracking-[.16em] text-[var(--muted)]">Food Rescue Network</span></span></button><nav className="hidden items-center gap-1 rounded-full border border-[var(--line)] bg-white/70 p-1 md:flex"><button onClick={()=>setTab("discover")} className={`nav-btn ${tab==="discover"?"nav-active":""}`}>Find food</button><button onClick={()=>requireAuth()&&setTab("donate")} className={`nav-btn ${tab==="donate"?"nav-active":""}`}>Share surplus</button><button onClick={()=>requireAuth()&&setTab("dashboard")} className={`nav-btn ${tab==="dashboard"?"nav-active":""}`}>My GiveBack</button></nav><div className="flex items-center gap-2">{user?<><span className="hidden max-w-40 truncate text-sm font-bold text-[var(--muted)] sm:block">{user.user_metadata?.display_name||user.email}</span><button onClick={signOut} className="button-secondary">Sign out</button></>:<button onClick={()=>{setAuthMode("signin");setAuthOpen(true)}} className="button-primary">Join free</button>}</div></div><div className="mx-auto flex max-w-7xl gap-1 px-5 pb-3 md:hidden">{[["discover","Find food"],["donate","Share surplus"],["dashboard","My GiveBack"]].map(([k,l])=><button key={k} onClick={()=>k==="discover"?setTab("discover"):requireAuth()&&setTab(k as typeof tab)} className={`nav-btn flex-1 ${tab===k?"nav-active":""}`}>{l}</button>)}</div></header>
 {notice&&<div className="mx-auto max-w-7xl px-5 pt-4 lg:px-8"><div role="status" className={`notice ${notice.kind==="ok"?"notice-ok":"notice-error"}`}>{notice.text}<button onClick={()=>setNotice(null)} className="ml-4 text-lg">×</button></div></div>}
 {tab==="discover"&&<section className="mx-auto max-w-7xl px-5 pb-16 pt-10 lg:px-8"><div className="hero-grid"><div className="hero-copy"><div className="eyebrow"><span className="dot"/>Rescue food before it goes to waste</div><h1>Good food should reach a person, not a bin.</h1><p className="hero-sub">GiveBack connects restaurants, shops, community groups and people with safe surplus food to nearby people who can collect it in time.</p><div className="hero-actions"><button className="button-primary button-large" onClick={()=>document.getElementById("food-feed")?.scrollIntoView({behavior:"smooth"})}>Find surplus food <span>↓</span></button><button className="button-ghost button-large" onClick={()=>requireAuth()&&setTab("donate")}>I have food to share</button></div><div className="trust-row"><span>🌱 Less waste</span><span>🤝 Community first</span><span>🌍 Worldwide-ready</span></div></div><div className="hero-card"><div className="hero-card-top"><span className="status-live">● LIVE</span><span>Open community listings</span></div><div className="big-number">{foods.length}</div><div className="big-label">surplus listings available right now</div><div className="mini-rule"/><div className="hero-stat-grid"><div><strong>Free</strong><span>No selling fees</span></div><div><strong>Local</strong><span>Pickup windows</span></div><div><strong>Simple</strong><span>Request → collect</span></div></div></div></div>
 <div id="food-feed" className="feed-head"><div><p className="section-kicker">Discover</p><h2>Food available near the community</h2><p>Search by food, city or country. Always check the pickup time and dietary notes before requesting.</p></div><button className="button-secondary" onClick={()=>refresh(user)}>{loading?"Refreshing…":"Refresh"}</button></div><div className="filters card"><div className="search-wrap"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search meals, bakery, groceries, city…"/></div><select value={type} onChange={e=>setType(e.target.value)}>{foodTypes.map(x=><option key={x}>{x}</option>)}</select><select value={country} onChange={e=>setCountry(e.target.value)}><option>All countries</option>{countries.map(x=><option key={x}>{x}</option>)}</select></div>
 {loading?<div className="empty card"><div className="spinner"/><h3>Loading live food listings…</h3><p>Connecting to the GiveBack community.</p></div>:filtered.length===0?<div className="empty card"><div className="empty-icon">🍃</div><h3>No matching food right now</h3><p>Try another search, country or food type — or be the first person to share surplus in your area.</p><button className="button-primary" onClick={()=>requireAuth()&&setTab("donate")}>Share surplus food</button></div>:<div className="food-grid">{filtered.map(food=><article className="food-card" key={food.id}><div className="food-image" style={food.image_url?{backgroundImage:`url(${food.image_url})`}:undefined}><span>{food.image_url?"":"🥗"}</span><div className="time-badge">{timeLeft(food.pickup_end)}</div></div><div className="food-body"><div className="food-meta"><span>{food.food_type}</span><span>{food.city}, {food.country}</span></div><h3>{food.title}</h3><p>{food.description}</p><div className="food-detail"><span>📦 {food.quantity}</span><span>🕐 {dateLabel(food.pickup_start)}</span></div>{food.dietary_info&&<div className="dietary">{food.dietary_info}</div>}<button className="button-primary full" onClick={()=>setSelected(food)}>View & request</button></div></article>)}</div>}
 <div className="how card"><div><p className="section-kicker">How it works</p><h2>Three steps. Real food rescued.</h2></div><div className="steps"><div><b>01</b><strong>Share surplus</strong><p>A donor posts what is available and when it can be collected.</p></div><div><b>02</b><strong>Request it</strong><p>A nearby person or community group sends a short request.</p></div><div><b>03</b><strong>Collect & complete</strong><p>The donor accepts one request, then both sides mark the handover complete.</p></div></div></div></section>}
 {tab==="donate"&&<section className="mx-auto max-w-5xl px-5 py-10 lg:px-8"><div className="page-intro"><p className="section-kicker">Share surplus</p><h1>Turn extra food into a useful moment.</h1><p>Post only food you can responsibly offer. Be clear about quantity, ingredients or dietary information, and the exact collection window.</p></div><form onSubmit={donate} className="form-card card"><div className="form-section"><div><h2>What do you have?</h2><p>Give people enough information to decide quickly.</p></div><div className="form-grid"><label>Title<input name="title" required minLength={3} maxLength={120} placeholder="e.g. 12 fresh bread rolls"/></label><label>Food type<select name="food_type" required>{foodTypes.slice(1).map(x=><option key={x}>{x}</option>)}</select></label><label className="wide">Description<textarea name="description" required minLength={10} maxLength={2000} rows={4} placeholder="What is it, when was it prepared or packed, and anything a collector should know?"/></label><label>Quantity<input name="quantity" required maxLength={120} placeholder="e.g. 12 portions"/></label><label>Dietary / allergen notes<input name="dietary_info" maxLength={500} placeholder="e.g. Contains dairy; vegetarian"/></label></div></div><div className="form-section"><div><h2>Where & when?</h2><p>Use a public pickup point or a safe location. Do not publish a private home address.</p></div><div className="form-grid"><label>Country<select name="country" required>{countries.map(x=><option key={x}>{x}</option>)}</select></label><label>City<input name="city" required minLength={2} maxLength={80} placeholder="e.g. Puchong"/></label><label>State / region<input name="region" maxLength={80} placeholder="e.g. Selangor"/></label><label>Pickup date<input name="pickup_date" type="date" required min={new Date().toISOString().slice(0,10)}/></label><label>Pickup starts<input name="pickup_start" type="time" required/></label><label>Pickup ends<input name="pickup_end" type="time" required/></label><label className="wide">Optional image URL<input name="image_url" type="url" placeholder="https://…"/></label></div></div><div className="form-foot"><span>By posting, you confirm the information is accurate and the food is offered in good faith.</span><button className="button-primary button-large" disabled={busy}>{busy?"Publishing…":"Publish surplus"}</button></div></form></section>}
 {tab==="dashboard"&&<section className="mx-auto max-w-7xl px-5 py-10 lg:px-8"><div className="page-intro compact"><p className="section-kicker">My GiveBack</p><h1>Your rescue activity.</h1><p>Manage food you have shared and requests you have made.</p></div><div className="dashboard-grid"><div className="dashboard-main card"><div className="dash-head"><div><h2>Requests on your food</h2><p>Choose one person to collect each available listing.</p></div><span className="count-pill">{incoming.length}</span></div>{incoming.length===0?<div className="dash-empty">No incoming requests yet.</div>:<div className="request-list">{incoming.map(c=><div className="request-row" key={c.id}><div className="avatar">{(c.message[0]||"G").toUpperCase()}</div><div className="request-copy"><strong>{c.message}</strong><span>{c.food_listings?.title} · {c.food_listings?.city}, {c.food_listings?.country}</span><small>{dateLabel(c.created_at)}</small></div><span className={`claim-status status-${c.status}`}>{c.status}</span>{c.status==="pending"&&<button className="button-primary" onClick={()=>acceptClaim(c)} disabled={busy}>Accept</button>}</div>)}</div>}</div><div className="dashboard-side"><div className="stat-card card"><span>Food you shared</span><strong>{owned.length}</strong><small>currently available</small></div><div className="stat-card card"><span>Your requests</span><strong>{outgoing.length}</strong><small>requests made</small></div><div className="card side-card"><h3>Your requests</h3>{outgoing.length===0?<p>No requests yet. Find food on Discover.</p>:outgoing.slice(0,6).map(c=><div className="mini-request" key={c.id}><div><strong>{c.food_listings?.title||"Food listing"}</strong><span>{c.status}</span></div>{c.status==="accepted"&&<button className="text-button" onClick={()=>updateClaim(c,"completed")} disabled={busy}>Mark collected</button>}{c.status==="pending"&&<button className="text-button" onClick={()=>updateClaim(c,"cancelled")} disabled={busy}>Cancel</button>}</div>)}</div></div></div></section>}
 <footer className="site-footer"><div className="mx-auto flex max-w-7xl flex-col gap-4 px-5 py-8 sm:flex-row sm:items-center sm:justify-between lg:px-8"><div><strong>GiveBack</strong><p>Food Rescue Network · A community project for reducing avoidable food waste.</p></div><div className="footer-note">Built with care · Worldwide-ready · Free to use</div></div><div className="created">Created by <strong>Koglesh R. Murugan</strong></div></footer>
 {selected&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setSelected(null)}><div className="modal card" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setSelected(null)}>×</button><div className="modal-image" style={selected.image_url?{backgroundImage:`url(${selected.image_url})`}:undefined}>{!selected.image_url&&"🥗"}</div><div className="modal-content"><div className="food-meta"><span>{selected.food_type}</span><span>{selected.city}, {selected.country}</span></div><h2>{selected.title}</h2><p>{selected.description}</p><div className="modal-facts"><div><small>Quantity</small><strong>{selected.quantity}</strong></div><div><small>Pickup</small><strong>{dateLabel(selected.pickup_start)} – {dateLabel(selected.pickup_end)}</strong></div>{selected.dietary_info&&<div><small>Dietary / allergens</small><strong>{selected.dietary_info}</strong></div>}</div>{user?.id===selected.donor_id?<div className="owner-warning">This is your listing. You cannot request your own food.</div>:<form onSubmit={e=>claimFood(e,selected)}><label>Message to the donor<textarea name="message" required minLength={5} maxLength={600} rows={4} placeholder="Tell the donor why you can collect it and any relevant context."/></label><button className="button-primary full button-large" disabled={busy}>{busy?"Sending…":"Request this food"}</button><p className="safety-note">For safety, arrange collection in a public or agreed location and avoid sharing sensitive personal information in the listing.</p></form>}</div></div></div>}
 {authOpen&&<div className="modal-backdrop" onMouseDown={e=>e.currentTarget===e.target&&setAuthOpen(false)}><div className="auth-modal card" role="dialog" aria-modal="true"><button className="modal-close" onClick={()=>setAuthOpen(false)}>×</button><div className="auth-mark">↗</div><p className="section-kicker">GiveBack account</p><h2>{authMode==="signin"?"Welcome back.":"Join the rescue network."}</h2><p>{authMode==="signin"?"Sign in to request food, share surplus and manage your activity.":"Create a free account to start rescuing or sharing surplus food."}</p><form onSubmit={submitAuth}>{authMode==="signup"&&<label>Name<input name="name" required minLength={2} placeholder="Your name or organization"/></label>}<label>Email<input name="email" type="email" required placeholder="you@example.com"/></label><label>Password<input name="password" type="password" required minLength={8} placeholder="At least 8 characters"/></label><button className="button-primary full button-large" disabled={busy}>{busy?"Please wait…":authMode==="signin"?"Sign in":"Create account"}</button></form><button className="switch-auth" onClick={()=>setAuthMode(authMode==="signin"?"signup":"signin")}>{authMode==="signin"?"New here? Create an account":"Already have an account? Sign in"}</button></div></div>}
 </main>;
}
