"use client";
import {useEffect,useState} from "react";import Link from "next/link";import {useParams} from "next/navigation";import {createClient} from "@/lib/supabase/client";import {useAuth} from "../../components/AuthProvider";import type {Listing} from "@/lib/types";
type Img={storage_path:string;sort_order:number};
export default function ListingPage(){const {id}=useParams<{id:string}>();const {user}=useAuth();const [item,setItem]=useState<Listing|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);
 useEffect(()=>{if(!id)return;const s=createClient();s.from("listings").select("*").eq("id",id).maybeSingle().then(async({data,error})=>{if(error)setError(error.message);if(data){const {data:imgs}=await s.from("listing_images").select("storage_path,sort_order").eq("listing_id",id).order("sort_order",{ascending:true}).limit(1);const first=imgs?.[0];setItem({...data as Listing,image_url:first?s.storage.from("listing-images").getPublicUrl(first.storage_path).data.publicUrl:null})}setLoading(false)})},[id]);
 async function request(){if(!user){location.href=`/login?next=/listing/${id}`;return}setBusy(true);const {error}=await createClient().from("requests").insert({listing_id:id,requester_id:user.id,message:"I would like to receive this item and can arrange a safe public handoff."});setMessage(error?error.code==="23505"?"You already requested this item.":error.message:"Request sent. The giver can review it from their dashboard.");setBusy(false)}
 async function chat(){if(!user){location.href=`/login?next=/listing/${id}`;return}setBusy(true);const {data,error}=await createClient().rpc("get_or_create_conversation",{p_listing_id:id});if(error)setMessage(error.message);else location.href=`/messages/${data}`;setBusy(false)}
 if(loading)return <main className="mx-auto max-w-4xl px-5 py-16">Loading…</main>;if(!item)return <main className="mx-auto max-w-4xl px-5 py-16"><div className="card p-8"><h1 className="text-2xl font-black">Listing unavailable</h1><p>{error||"This listing may have been removed."}</p></div></main>;const own=user?.id===item.owner_id;
 return <main className="mx-auto max-w-5xl px-5 py-10"><Link href="/" className="font-bold underline">← Back</Link><div className="mt-6 grid gap-8 md:grid-cols-2"><div className="card overflow-hidden"><div className="aspect-square bg-[#e8e2d5]">{item.image_url?<img src={item.image_url} alt={item.title} className="h-full w-full object-cover"/>:<div className="grid h-full place-items-center text-8xl">🎁</div>}</div></div><div><p className="text-xs font-black uppercase tracking-widest text-[var(--leaf)]">{item.category}</p><h1 className="mt-2 text-4xl font-black">{item.title}</h1><p className="mt-4 whitespace-pre-wrap text-[var(--muted)]">{item.description}</p><div className="mt-6 rounded-2xl border bg-white/50 p-5 text-sm space-y-2"><p><b>Condition:</b> {item.condition}</p><p><b>Location:</b> {item.city}{item.state?`, ${item.state}`:""}, {item.country}</p><p><b>Status:</b> {item.status}</p>{item.pickup_notes&&<p><b>Pickup:</b> {item.pickup_notes}</p>}</div>{!own&&item.status==="active"&&<div className="mt-6 grid gap-3"><button disabled={busy} onClick={request} className="rounded-xl bg-[var(--leaf)] p-3 font-black text-white">Request this item</button><button disabled={busy} onClick={chat} className="rounded-xl border p-3 font-black">Private chat with giver</button></div>}{own&&<Link href="/dashboard" className="mt-6 block rounded-xl bg-[var(--ink)] p-3 text-center font-black text-white">Manage this listing</Link>}{message&&<p className="mt-4 rounded-xl bg-white p-3 text-sm">{message}</p>}</div></div></main>}
