export type Database = {
 public: { Tables: {
 profiles:{Row:{id:string;display_name:string;username:string|null;avatar_url:string|null;bio:string|null;city:string|null;state:string|null;country:string|null;is_organization:boolean;organization_name:string|null;created_at:string;updated_at:string};Insert:{id:string;display_name:string;username?:string|null;avatar_url?:string|null;bio?:string|null;city?:string|null;state?:string|null;country?:string|null;is_organization?:boolean;organization_name?:string|null};Update:Partial<Database["public"]["Tables"]["profiles"]["Insert"]>};
 listings:{Row:{id:string;owner_id:string;title:string;description:string;category:string;condition:"new"|"like_new"|"good"|"fair";city:string;state:string|null;country:string;pickup_notes:string|null;status:"active"|"reserved"|"completed"|"expired"|"removed";created_at:string;updated_at:string;expires_at:string|null};Insert:{owner_id:string;title:string;description:string;category:string;condition:"new"|"like_new"|"good"|"fair";city:string;state?:string|null;country?:string;pickup_notes?:string|null;status?:"active"|"reserved"|"completed"|"expired"|"removed"};Update:Partial<Database["public"]["Tables"]["listings"]["Insert"]>};
 listing_images:{Row:{id:string;listing_id:string;storage_path:string;sort_order:number;created_at:string};Insert:{listing_id:string;storage_path:string;sort_order?:number}};
 requests:{Row:{id:string;listing_id:string;requester_id:string;message:string;status:"pending"|"accepted"|"declined"|"cancelled"|"completed";created_at:string;updated_at:string};Insert:{listing_id:string;requester_id:string;message:string;status?:"pending"|"accepted"|"declined"|"cancelled"|"completed"};Update:Partial<Database["public"]["Tables"]["requests"]["Insert"]>};
 conversations:{Row:{id:string;listing_id:string|null;request_id:string|null;participant_a:string;participant_b:string;created_at:string;updated_at:string};Insert:{listing_id?:string|null;request_id?:string|null;participant_a:string;participant_b:string};Update:Partial<Database["public"]["Tables"]["conversations"]["Insert"]>};
 messages:{Row:{id:string;conversation_id:string;sender_id:string;body:string;created_at:string;read_at:string|null};Insert:{conversation_id:string;sender_id:string;body:string;read_at?:string|null}};
 notifications:{Row:{id:string;user_id:string;type:string;title:string;body:string;listing_id:string|null;request_id:string|null;read_at:string|null;created_at:string};Insert:{user_id:string;type:string;title:string;body:string;listing_id?:string|null;request_id?:string|null}};
 saved_listings:{Row:{user_id:string;listing_id:string;created_at:string};Insert:{user_id:string;listing_id:string}};
 reports:{Row:{id:string;reporter_id:string;listing_id:string|null;reported_user_id:string|null;reason:string;status:string;created_at:string};Insert:{reporter_id:string;listing_id?:string|null;reported_user_id?:string|null;reason:string;status?:string}};
 } ; Enums:{item_condition:"new"|"like_new"|"good"|"fair";listing_status:"active"|"reserved"|"completed"|"expired"|"removed";request_status:"pending"|"accepted"|"declined"|"cancelled"|"completed"}};
};
